### ISSUE TITLE
Introduzir uma frase de término de viagem

### ISSUE THREAD

**Issue by ScriptForAll** [carrismetropolitana/tts#11]
Na operação pré-CMet a RL tinha no seu sistema uma mensagem de fim de viagem. 
Dizia "(Nome da paragem terminal). Fim de Percurso. Obrigado por viajar connosco!"

Apesar de ser um pequeno detalhe é algo que torna uma viagem de autocarro mais apelativa. Como é de simples implementação creio que seja algo a ser considerado para melhorar a experiência do passageiro dentro da Carris Metropolitana.

**Comment by joao-vasconcelos** [comment]
Olá @ScriptForAll, os sons estão criados e está pensado implementar: https://storage.carrismetropolitana.pt/static/tts/live/common/
