### ISSUE TITLE
[SUGESTÃO] - Possibilidade de o TTS separar os números de EN/CM/Entre Outros dos números de polícia

### ISSUE THREAD

**Issue by JBIMEC** [carrismetropolitana/tts#12]
Olá, haverá a possibilidade de o TTS, conseguir separar os número de Estrada Nacionais, Caminhos Municipais, entre outros dos números de polícia. 

Por exemplo, em Alcochete, na paragem "S FRANCISCO (EN 119 31)" - **010059**, o TTS lê "São Francisco, Estrada Nacional cento e dezanove, trinta e um", já na paragem "S FRANCISCO (EN 119 114)" - **010066**, o TTS lê "São Francisco, Estrada Nacional cento e dezanove mil cento e catorze". Isto, para mim é estranho devido ao espaço do tt_stop_name, que consta no arquivo stops.txt, aparece igual:
![image](https://github.com/carrismetropolitana/tts/assets/162840279/02ac8796-1928-491f-83d4-e5cfadca8568)
![image](https://github.com/carrismetropolitana/tts/assets/162840279/1f6b2864-2941-4b3f-8026-b9c369ca569e)
Isto não acontece só na área 4, também na área 1, como já foi referido no problema carrismetropolitana/gtfs#242, e na mesma área, na paragem **172353** - "EN 247 43", o TTS lê tal e qual como lê a paragem **010059**

**Comment by ricardojorgerm** [comment]
O leitor de texto infelizmente não é "obediente" ao texto fornecido, tendo já tentado várias soluções diferentes para forçar a leitura dos números distintos. Como existem estradas nacionais compostas por mais de um número, nem sempre é apenas uma questão de número de polícia. É definitivamente uma área em progresso. 
Lamento pelo facto de não estar correto e agradeço a sua observação oportuna, irei manter o issue aberto para referenciar este problema futuramente.

**Comment by JBIMEC** [comment]
De nada

**Comment by joao-vasconcelos** [comment]
Todas as paragens estão em processo de "renomeação" e este é um tema que está a ser tido em conta. Não será uma correção para breve, mas é algo que está a ser tratado.

**Comment by JBIMEC** [comment]
Olá, obrigado pela solução deste problema, @ricardojorgerm e @joao-vasconcelos, aguardo então a atualização do GTFS/TTS!
