### ISSUE TITLE
Associação de "Trind" a "Trindade"

### ISSUE THREAD

**Issue by stgarmm** [carrismetropolitana/tts#14]
Olá, será possível, associar sempre a abreviação "Trind" à palavra "Trindade". Isto deve-se ao facto de na paragem **030053** - "R Trind Coelho (X) Pcta Conde Arnoso)", o leitor de texto, em vez de se de referir a "Trindade", lê o que está escrito, ou seja "Cruzamento entre Rua Trind Coelho e Praceta Conde Arnoso"

**Comment by ricardojorgerm** [comment]
Penso que é bastante aceitável integrar no TTS para conhecer essa abreviatura. Embora esta aplique-se apenas numa paragem, penso que é interessante de ter como outros nomes e é bastante específico.
