### ISSUE TITLE
Abreviaturas extraídas automaticamente por meios computacionais

### ISSUE THREAD

**Issue by ricardojorgerm** [carrismetropolitana/tts#15]
As seguintes abreviaturas podem ser codificadas com base no estudo de paragens atuais via análise de combinações únicas.
Terão de ser sujeitas a análise manual para conferir que as abreviaturas não introduzem regressões noutras abreviaturas já codificadas:

- [x]  ['Acad', 'Academia'], 
- [x]  ['Algaz', 'Algazarra'], 
- [x]  ['Alped', 'Alpedr', 'Alpedrinha'],
- [x]  ['Anast', 'Anastácio'],
- [x]  ['Bartol', 'Bartolomeu'], 
- [x]  ['Celest', 'Celestino'],
- [x]  ['Coe', 'Coelho'], 
- [x]  ['Combat', 'Combatentes'], 
- [x]  ['Comercian', 'Comerciantes'], 
- [x]  ['Concel', 'Concelho'], 
- [x]  ['Condom', 'Condomínio'], 
- [x]  ['Descobrim', 'Descobrimentos'], 
- [x]  ['Doming', 'Domingos'], 
- [x]  ['Estaciona', 'Estacionamento'], 
- [x]  ['Eucalip', 'Eucaliptos'], 
- [x]  ['Felic', 'Feliciano'], 👎 Excluí "Fel" pois é uma palavra válida que poderá surgir na toponímia.
- [x]  ['Florb', 'Florbela'],
- [x]  ['Fut', 'Futebol'], 
- [x]  ['Garret', 'Garrett'], 
- [x]  ['Grand', 'Grande'],  👎 Foneticamente, tanto faz.
- [x]  ['Guilh', 'Guilherme'], 
- [x]  ['Hiper', 'Hipermercado'], 👎 Conflito com Hiper Cascais cujo nome é assim conhecido
- [x]  ['Hot', 'Hotel'], 
- [x]  ['Intern', 'Internacional'], 
- [x]  ['Lat', 'Latino'],  
- [x]  ['Lenc', 'Lencastre'], 
- [x]  ['Macolid', 'Macolide'], 
- [x]  ['Madal', 'Madalena'], 
- [x]  ['Magal', 'Magalhães'],
- [x]  ['Mauri', 'Mauricio'], 👎 Deteção errada, antigo nome da fábrica MAURI FERMENTOS
- [x]  ['Mendo', 'Mendonça'],  👎 Deteção errada, existe uma Rua Mendo de Gomes Seabra. 
- [x]  ['Mirad', 'Miradouro'], 
- [x]  ['Misericórd', 'Misericórdia'],
- [x]  ['Mouz', 'Mouzinho'], 
- [x]  ['Nac', 'Nacional'], 👎 Já proposto, tem conflito com Avenida do NAC 
- [x]  ['Naveg', 'Navegantes'],
- [x]  ['Op', 'Operário'], 👎 Deteção errada, devia ser "Serv Op" (serviços operacionais)
- [x]  ['Petró', 'Petrónio'],
- [x]  ['Polidesp', 'Polidesportivo'], 
- [x]  ['Prac', 'Praceta'], 
- [x]  ['Prep', 'Preparatória'],
- [x]  ['Pólv', 'Pólvora'], 
- [x]  ['Repúbl', 'República'], 
- [x]  ['Resid', 'Residence'],
- [x]  ['Saram', 'Saramago'],
- [x]  ['Serv', 'Serviço'], 👎 Deteção errada, devia ser "Serv Op" (serviços operacionais)
- [x]  ['Silvest', 'Silvestre'], 
- [x]  ['Soeir', 'Soeiro'], 
- [x]  ['Sup', 'Super', 'Supermercado'],  👎 Na verdade, era abreviatura de "Superior" que foi adicionado
- [x]  ['Tap', 'Tapada'], 
- [x]  ['Tras', 'Traseiras'], 
- [x]  ['Trind', 'Trindade'], 
- [x]  ['Unid', 'Unidade'], 
- [x]  ['Veriss', 'Verissimo'], 
- [x]  ['Vet', 'Veterinário'], 
- [x]  ['Ág', 'Água']

**Comment by joao-vasconcelos** [comment]
Wooow incrível 🫶
