### ISSUE TITLE
Pronúncia errado de "Pacheca"

### ISSUE THREAD

**Issue by stgarmm** [carrismetropolitana/tts#16]
Olá, o TTS, em vez de pronunciar "Pacheca" (sem acentuação no "e"), pronuncia "Pachéca", como se o "e" tivesse acentuação, o que está errado!

**Comment by ricardojorgerm** [comment]
Tendo sido apanhado pelo Montachique que se lê Montáchique, pelo Samouco que se lê Sámouco, pensei, desta vez, que talvez fosse melhor conferir se era Pachéca ou Pachêca. Já falei com um samouquence que me conferiu a pronúncia que reportou.

**Comment by stgarmm** [comment]
Obrigado pela correção @ricardojorgerm!
