### ISSUE TITLE
Corrigir 050227

### ISSUE THREAD

**Issue by ricardojorgerm** [carrismetropolitana/tts#19]
O algoritmo de cruzamentos identificou erroneamente a indicação onde cruza

**Comment by ricardojorgerm** [comment]
https://on.carrismetropolitana.pt/stops/050227

**Comment by stgarmm** [comment]
Olá @ricardojorgerm, reparei que o mesmo acontece na paragem 050228. E uma sugestão, já que ambas as paragens se encontram num cruzamento, o nome poderia ficar, só simplesmente "R das Tojas (X) R Bocage".
