### ISSUE TITLE
Desambiguação de "Cons" para "Consultas"

### ISSUE THREAD

**Issue by stgarmm** [carrismetropolitana/tts#20]
Olá, reparei que o TTS na paragem 021064 "Hosp. Garcia de Orta (Cons. Externas)", lê tal e qual como está escrito, ou seja "Cons Externas". Seria possíval desambiguar sempre "Cons" para "Consultas", ou iria ser conflito com outras abreviaturas?

**Comment by ricardojorgerm** [comment]
Existe conflito: Cons para Conselheiro, que é aceite como abreviatura de toponímia por exemplo no manual de endereçamento dos CTT (página 15, em linha: https://www.ctt.pt/application/themes/pdfs/empresas/manual_enderecamento_abr_2018.pdf).

https://github.com/carrismetropolitana/tts/blob/3249aa64e09720006608d44e16c5e61a1cebbae8/lib/makeText.js#L621-L622

Exemplo em paragem: https://beta.carrismetropolitana.pt/stops/060329

Talvez possa especificar uma abreviatura de contexto específica para este caso, mas confesso que seria provavelmente apenas aplicável unicamente a esta paragem. Não seria certamente o único caso de uma abreviatura para paragem única, mas se possível, tento construir regras que possam legitimamente ser aplicáveis a futuros casos e não apenas às paragens presentes.

**Comment by ricardojorgerm** [comment]
Acabei por implementar para retirar a exceção a Ext que existia em Conselheiro, ficando uma abreviatura 2 em 1, desde que não haja nenhum Hospital com o nome conselheiro, há-de funcionar.

**Comment by stgarmm** [comment]
Obrigado!
