### ISSUE TITLE
Associação "J Malhoa" para "José Malhoa"

### ISSUE THREAD

**Issue by JBIMEC** [carrismetropolitana/tts#21]
Boa noite, reparei que nas paragens "AV CALOUSTE GULBENK (ACESSO AV J MALHOA)" - **060017** e **060018**, o TTS não desambigua J para José. Será possivel desambiguar "J Malhoa" para "José Malhoa" sempre?

**Comment by ricardojorgerm** [comment]
Penso que sim, já que é comum na toponímia portuguesa. Em geral, tem sido impossível distinguir J entre João e José a não ser em nomes particulares que sejam comuns na toponímia (J Saramago, por exemplo). 
Assim não se pretende distinguir todos os J abreviados pois é possível que se incorra em erro.
