### ISSUE TITLE
Pronúncia errada de "C. Universitária" no TTS (patterns)

### ISSUE THREAD

**Issue by stgarmm** [carrismetropolitana/tts#23]
Olá, reparei que na parte do TTS (patterns), a linha 3702, com destino à Cidade Universitária, em vez de dizer "Cidade Universitária" diz "Casal Universitária"! Será pelo titulo do destino (no site) estar C Universitária?

TTS: https://storage.carrismetropolitana.pt/static/tts/live/patterns/3702_0_1.mp3 

![image](https://github.com/carrismetropolitana/tts/assets/158851698/f9baf9df-ba6c-4208-a8d9-0bb35a316a15)

**Comment by ScriptForAll** [comment]
Sugiro que se passe de `C. Universitária` para `Cid. Universitária`

**Comment by ricardojorgerm** [comment]
@joao-vasconcelos seria muito impeditivo pedir a mudança de nome de linha para Cid. aos produtores de dados (operadores)? a letra C está super pesada e gostava de evitar adicionar imensas exceções de contexto (Centros, Casais, Casas, Cidades, etc.)

de qualquer forma irei olhar para o assunto

**Comment by stgarmm** [comment]
Obrigado pela Correção, @ricardojorgerm!
