### ISSUE TITLE
Pronúncia errada de Outão

### ISSUE THREAD

**Issue by stgarmm** [carrismetropolitana/tts#27]
Olá, reparei que o TTS, em vez de pronunciar "Outão", pronúncia "Autão", penso que a forma como o TTS lê está incorreta, devendo de ser corrigido!

**Comment by ricardojorgerm** [comment]
Sim, verifico que o leitor que usamos da Google tem esse problema
https://translate.google.com/?sl=pt&tl=en&text=Outão&op=translate

Penso que está a ir buscar a fonética inglesa para "out"

Vou corrigir

**Comment by ricardojorgerm** [comment]
Como indicado na descrição, este projeto é voluntário (eu propus à CMet que assim fosse) porque sentia que seria importante garantir a leitura correta das paragens complexas em prol das pessoas cegas ou amblíopes, de uma forma aberta e da comunidade, em vez de fechada, até para que possa ser usada noutras valências se assim quiserem.
Gosto muito de receber as suas contribuições e convido a que, se assim conseguir ou for capaz, envie as alterações para PR que considere necessárias no código.

**Comment by stgarmm** [comment]
Olá @ricardojorgerm , agradeço desde já as suas palavras. Muito obrigado por resolver este problema.
Já em relação em enviar as alterações para PR, não consigo fazer! Mas continuarei a enviar issue's sempre que detetar algum errado.
Cumprimentos e muito obrigado!
