### ISSUE TITLE
Desambiguação de USF

### ISSUE THREAD

**Issue by JBIMEC** [carrismetropolitana/tts#28]
Olá, será que o TTS, poderá sempre desambiguar "USF" para "Unidade de Saúde Familiar"? Ou haverá conflito com algum nome?

**Comment by ricardojorgerm** [comment]
Olá JBIMEC
A abreviatura em questão é por um lado cristalizada na oralidade (as pessoas falam "ú ésse éffe") e sua leitura por extenso parece-me bastante técnica. 
Tendo em atenção esta questão, talvez lhe peça uma sugestão: seria aceitável lermos USF como Centro de Saúde? Parece-me que seria uma alternativa bastante acessível e de fácil compreensão.

**Comment by JBIMEC** [comment]
Olá @ricardojorgerm sim, parece-me que seria uma alternativa acessível e de fácil compreensão! Pode ser!

**Comment by JBIMEC** [comment]
Muito obrigado. 👍

**Comment by ricardojorgerm** [comment]
De nada, acabei por preservar como Unidade de Saúde, espero que seja ok.

**Comment by JBIMEC** [comment]
@ricardojorgerm claro, sem problemas, fique descansado. 👍

**Comment by joao-vasconcelos** [comment]
Eu por acaso gosto mais de Centro de Saúde. Acho que é menos formal, mais próximo.
