### ISSUE TITLE
Indicação de Plataformas (P1, P2, etc.)

### ISSUE THREAD

**Issue by joao-vasconcelos** [carrismetropolitana/tts#3]
- [ ] Lisboa (Sete Rios) P8 -> Lisboa (Sete Rios) Plataforma 8

**Comment by ricardojorgerm** [comment]
Após uma breve sondagem de utilizadores, conclui-se que:
- A sonorização de "Pê" afigura-se bastante
- Não existe consenso universal sobre a abreviação correta que a letra representa:
   - Pista
   - Paragem
   - Plataforma
   - Praça
- Para além de que por vezes se refere ao que é efetivamente um Cais ou outro nome de arte
- Conclui-se pois que a letra é em si mesma clara e uma forma expediosa de comunicar verbalmente o local de embarque ou desembarque; e que a sua substituição por uma das alternativas poderia confundir os que preferem um dos outros vocábulos (ou que em certas estações ou locais, existam preferências ou arte prévia de uso de um dos vocábulos especificamente).

**Comment by joao-vasconcelos** [comment]
Apesar do nome correto ser indiscutivelmente **_Plataforma_**, e desta ser uma oportunidade de unificação do significado da letra P no nosso idioma, aceito a decisão de manter a situação ambígua atual para encurtar o tempo de leitura de cada paragem.
