### ISSUE TITLE
[Sugestão] Adicionar 'dos', 'das', 'da', etc.

### ISSUE THREAD

**Issue by joao-vasconcelos** [carrismetropolitana/tts#4]
Exemplo:

Qta Fonte -> Quinta **da** Fonte

**Comment by ricardojorgerm** [comment]
Infelizmente não existe nenhuma regra na lingua portuguesa que permita fazer isto de uma forma sistemática. Vendo as palavras "Quinta" e "Fonte", nenhuma delas é sistematicamente precedida ou sucedida do artigo demonstrativo, exemplo:

- Quinta Mariano
- Bela Fonte

Portanto, seria necessário associar o artigo demonstrativo a pares específicos de palavras exaustivamente listadas, que é um problema intractável.

Até que exista uma base de dados de referência para tais localidades, essa funcionalidade não será possível, e o programa TTS pretende criar um sistema automático que se aproxime de forma sistemática o mais perto possível de uma versão legível da paragem escrita, mas não pretende substituir a revisão que poderá ser necessária em casos que não sejam escaláveis para várias paragens.

**Comment by joao-vasconcelos** [comment]
Got it. Obrigado!
