### ISSUE TITLE
Leitura incorreta de paragens (Prior Velho)

### ISSUE THREAD

**Issue by brazanet** [carrismetropolitana/tts#5]
Pelo que detetei, nas paragens que tenham Prior no nome o TTS lê o nome de uma forma que se assemelha a inglês (praior em vez de prior).
Um exemplo: https://beta.carrismetropolitana.pt/stops/071539

**Comment by ricardojorgerm** [comment]
Corrigido no código 👍 
A próxima vez que houver atualização de sons, serão gerados corretamente. Obrigado.
