### ISSUE TITLE
[Sugestão] Adicionar o termo "número" ao TTS

### ISSUE THREAD

**Issue by brazanet** [carrismetropolitana/tts#6]
Sugeria a adição do termo "número" precedendo qualquer numeração de uma porta, tal torna a leitura mais fluída e mais natural. De forma a automatizar o processo seriam excluídos os casos em que o número é imediatamente precedido por Av, Rua ou EN: 
"Av 25 Abril 18B" passaria a ser lido como "Avenida 25 Abril número 18B"
https://beta.carrismetropolitana.pt/stops/170906
"EN 117" manter-se-ia como "Estrada Nacional 117"
https://beta.carrismetropolitana.pt/stops/170843

**Comment by ricardojorgerm** [comment]
Olá. 
Obrigado pela sugestão. 
Implementei código para resolver este assunto parcialmente.
Em vias que celebram datas, concordo que seja relevante porque tipicamente já se enunciou o número da data ("25" em 25 de abril); por isso, ser explícito sobre qual é o número de polícia ajuda a quebrar o padrão e a esclarecer esse número.
Exemplo já no site: https://beta.carrismetropolitana.pt/stops/010023
Mais genericamente noutras vias que não possuem datas, torna-se mais difícil assegurar que não existem conflitos.
