### ISSUE TITLE
[A1] - Pronúncia incorreta das paragens da "R das Fisgas"

### ISSUE THREAD

**Issue by JBIMEC** [carrismetropolitana/tts#7]
Nas paragens: **"R das Fisgas (Fte Hiper Cascais)"** - 050201 e 050202; **"R Fisgas 661"** - 050200; **"R das Fisgas (X) R São Francisco"** - 050199; **"R das Fisgas (Baviera)"** - 050339; **"R das Fisgas (Fte Baviera)"** - 050340; e **"R das Fisgas (X) Rotunda"** - 050341, o tts pronuncia erradamente o "Fisgas", lendo-o como "Fisgás". Neste nome o "a" não se lê "á" (ou seja, sem acentuação). 

Haverá alguma forma de corrigir este erro?

**Comment by JBIMEC** [comment]
Olá @ricardojorgerm, obrigado!

**Comment by ricardojorgerm** [comment]
Olá @JBIMEC vou aguardar pela confirmação quando sair no novo GTFS. Este não foi fácil de corrigir. Considera este commit uma primeira tentativa.

**Comment by JBIMEC** [comment]
Olá @ricardojorgerm ok, e já é possível prever para quando a saída do novo GTFS?

**Comment by joao-vasconcelos** [comment]
Olá @JBIMEC, vai ser atualizado agora. Hoje ao final do dia o som atualizado deve estar visível no site.

**Comment by JBIMEC** [comment]
Olá @joao-vasconcelos já vi, obrigado pela atualização/atualização do som!

**Comment by JBIMEC** [comment]
Olá @ricardojorgerm verifiquei agora, passado algum tempo, que a leitura de `Fisgas` ficaria mais correta como a leitura de `Queijas`, como consta no issue #25 !

**Comment by JBIMEC** [comment]
Olá, @ricardojorgerm reparei agora depois deste tempo, que o "Fisga-as", deixa a pronúncia um pouco forçada! Penso que colocanco "Fisgâs" ficaria melhor. Tal como foi feito com o issue #25!
