### ISSUE TITLE
Pronúncia incorreta do nome Mcdonald's

### ISSUE THREAD

**Issue by stgarmm** [carrismetropolitana/tts#9]
Enquanto que nas paragens "CH CAPARICA (R ANT ANDRADE) MCDONALD'S" - **020341** e **020342**, na área 3, o pronúncia está correta. Já na paragem da área 1 "Estr Mercês Mcdonald 's" - **170254**, o TTS lê "Mcdonald - s", (como se o "s" fosse outra palavra).  Isto acontecerá, devido à existência de um espaço entre "Mcdonald" e o "'s", ou será algo diferente?

![image](https://github.com/carrismetropolitana/tts/assets/158851698/8570a99a-6bdb-4df6-954b-72b51d9032dc)
![image](https://github.com/carrismetropolitana/tts/assets/158851698/47b4b070-ce9e-4833-9bd7-4494af1481fb)

**Comment by ricardojorgerm** [comment]
Olá @joao-vasconcelos, este espaço está incorreto, poderiam corrigir?
Paragem 170254
